workflows:
  vibe-player-android:
    name: Vibe Player Android
    max_build_duration: 60

    environment:
      groups:
        - google_play
      android_signing:
        - paliaapk-release

    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Build signed APK
        script: |
          flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk

    publishing:
      email:
        recipients:
          - shanpalia786@gmail.com
